### ISSUE TITLE
Do not suppress accessibility services

### ISSUE THREAD

**Issue by goharanwar** [openatx/android-uiautomator-server#10]
In newer uiautomator versions 2.1.2 onwards there is a new option which allow not to suppress accessibility services. Currently when this json prc server is running on device we cant execute any uiautomator command using adb e.g we cant run 
`adb shell uiautomator dump`
If we use the following flag we might use the existing accessibility services without killing them
//`FLAG_DONT_SUPPRESS_ACCESSIBILITY_SERVICES`
`this.uiAutomation = InstrumentationRegistry.getInstrumentation().getUiAutomation(UiAutomation.FLAG_DONT_SUPPRESS_ACCESSIBILITY_SERVICES);`

**Comment by darran-kelinske-fivestars** [comment]
why wontfix?

**Comment by mingyuan-xia** [comment]
explained clearly

**Comment by dazza5000** [comment]
Those are two different method signatures though:

`UiAutomation uiAutomation = instrumentation.getUiAutomation();`

`    public UiAutomation getUiAutomation(@UiAutomationFlags int flags) {`

**Comment by codeskyblue** [comment]
Tried again.

Set configurator in setUp method, still useless.

```java
@Before
    public void setUp() throws Exception {
        Configurator.getInstance().setUiAutomationFlags(
                Configurator.getInstance().getUiAutomationFlags() | UiAutomation.FLAG_DONT_SUPPRESS_ACCESSIBILITY_SERVICES);
```
