### ISSUE TITLE
parent() method not implemented

### ISSUE THREAD

**Issue by xxxxlr** [openatx/android-uiautomator-server#11]
Hey @codeskyblue 
Thanks for maintaining the app! It is quite a handy tool!

I am building an app using it but stucking at missing 'd.parent()' method when trying to access the node's parent. So i want to implemente this method.

From the code of uiautomator2, the python wrapper, it is commented that it has to implement a 'parent' method in this android-uiautomator-server app.

I tried to see where the code is located. It seems it should be in stub/Selector.java. 
Reading this class, I got confused by 'getChildOrSibling'.

But to be honest, I don't really know what I am doing , I was hoping to write some 'parralle' function, something like child(), but there's no such method...and I got lose...

To fiture it out, I have some questions regarding the function calling processes and I am hoping you can help me to understand them and I can start to contribute as well, if you have time :)

1. I setted d.debug to true from python uiautomator2 and I saw the all the requests and responses. And I can see there's 'method' field. And after sending it to androiud-uiautomater-server, how does the server accept the request? Where is the server accepting point?

2.  I cloned the project to my local env and tried to build it. I followed the build session from README.md
At the project root, I did

```bash
$ ./gradlew build
$ ./gradlew packageDebugAndroidTest
```
No error so far.

But running ./gradlew cC, the terminal stucked at 

```
<============-> 95% EXECUTING [2m 53s]
> :app:connectedDebugAndroidTest
```
Is this normal? 

And I open another terminal to run:

```
adb forward tcp:9008 tcp:9008 # tcp forward
```
and then 
```
adb shell am broadcast -a ADB_INPUT_TEXT --es text SGVsbG8g5L2g5aW9
``` 
But the text field in my app didn't have any text inserted.

So, I am not sure if I build sucessfully or not. 
Also I changed one method in Selector.java

```java
	public String getText() {
		Log.d("should always return this text");
		return "should always return this text";
	}
```

So when I send a d(xx).get_text(), it should always got the given texts. However that's not what happed.
I am not sure if it's a build issue or this is just not how it 

Other than these two questions, if you have any insight you want to share, please let me know.
Thanks again for your time.

Ran

**Comment by mingyuan-xia** [comment]
> Is this normal?

Yes, it is a server app, running eternally on the device unless you kill it.
I dont think the broadcast channel is working now. I did not find any code receiving `-a ADB_INPUT_TEXT`.
Instead, you should connect to `:9008` and command uiautomator-server with REST APIs.

**Comment by xxxxlr** [comment]
@mingyuan-xia ,
Thanks for the replay. That's good to know.

And would you mind explaining a bit more about how should I go for implementing a method for get the parent of a node?

**Comment by codeskyblue** [comment]
Do you using QQ (499563266)? @xxxxlr

**Comment by codeskyblue** [comment]
This is my way how to develop and test this repo.

After inited with `python -m uiautomator2 init`. Open App
![image](https://user-images.githubusercontent.com/3281689/41693308-52c3cfd8-7537-11e8-8506-327919e342f3.png)

shutdown UIAutomator keeper(atx-agent) by click
![image](https://user-images.githubusercontent.com/3281689/41693139-85548506-7536-11e8-88b5-958c9371112e.png)

Usally I don't use cmdline. Instead I open AndroidStudio select file and edit
![image](https://user-images.githubusercontent.com/3281689/41693197-c21607da-7536-11e8-9ff8-84ce4c618ac5.png)

And Click button to Run test
![image](https://user-images.githubusercontent.com/3281689/41693103-57563da2-7536-11e8-8e85-7d2d8c3550bb.png)

If everything goes fine. You should see
![image](https://user-images.githubusercontent.com/3281689/41693223-dad5690a-7536-11e8-9d26-1d412bd6c54d.png)

Open Python type some test code, it should looks fine.
![image](https://user-images.githubusercontent.com/3281689/41693244-f9f351bc-7536-11e8-95ff-3a3464864000.png)

**Comment by xxxxlr** [comment]
@codeskyblue 
We actually chated through QQ yesterday after I posed this question :) But our conversitions got burried there...

Now, I am able to run my local version of uiautomator-server, I can see the method I added, getParent,  in the AutomatorServiceImpl got called.

Thanks for the help :).

But I am stuck on another problem for getParent.
Since getParent is on UiObject2, I need to convert the the result of getParent()（which is a UiObject2 object）to UiObject in order to add it to the cach hashmap：　ConcurrentHashMap<String, UiObject> uiObjects

Here is my modification:

AutomatorServiceImpl.java:

```java
    @Override
    public String getParent(String obj) throws UiObjectNotFoundException {
        Log.d("OKOKOK getParent");
        UiObject ui = uiObjects.get(obj);
        if (ui.toUiObject2() == null) {
            Log.d("UiObject does not support getParent");
            return null;
        } else {
            UiObject2 parent = ui.toUiObject2().getParent();
//            TODO:how to convert UiObject2 to UiObject ? It's possible to add a method : toUiObject in Selector class, but that 's from a selector, I can not find a link between UiObject2 to UiSelector.
            // convertedParent = convertUiObject2ToUiObject(parent)
            return addUiObject(convertedParent);
        }
    }

```
Do you guys have a better idea of how to achieve this?

**Comment by codeskyblue** [comment]
what is the difference betwr uiobject and uiobject2

**Comment by xxxxlr** [comment]
From the surface, I only see the difference between their API. 

Also in order to create a uiObject, you need a  UiSelector, and for a UiObject2, you need a BySelector. And I don't see how you can construct one from another. 

So I am out of ideas now.

Any thoughts? @codeskyblue @mingyuan-xia

**Comment by codeskyblue** [comment]
There are some methods

1. Convert UiObject2 to UiObject
2. Create another HashMap
3. Use Object as HashMap Value
4. ...

**Comment by xxxxlr** [comment]
But thanks for the insightful ideas @codeskyblue.

1. I believe this is the best way and I added a stub function in the previous question statement to illustrate what I meant. And it might just have no better way to do this...
2. I tried this approach, however, when later on you want to getUiObject, I believe you either have to add another function, getUiObject2. It's possible, but there are 20 occurance of getUiObject...But maybe this is the way...after all, the lib has to be back compitable with UiObject.
3. I don't think this approach will pass the code review...

**Comment by codeskyblue** [comment]
looks like it is really hard to implement this function. Tell me how you going to use it if implemented, let's see if there is another way to do it

**Comment by xxxxlr** [comment]
Thanks @codeskyblue, @mingyuan-xia 
I started to implement it as a dedicated function on server which works ok. However what I did breaked the convension of this lib which is to mimic the native uiAutomator/2 API. 

So I don't think I will PR and I will close it for now. But I do appriciated you guys spending time on this issue.

**Comment by codeskyblue** [comment]
it's still ok to make a pr, just want to know how did you do it.

**Comment by xxxxlr** [comment]
Hey @codeskyblue ,

I didn't solve the problem of implementing 'getParent', I just skipped it and hide it in a function on the uiautomater-server size... which has no value for a pr... :( 

https://github.com/xxxxlr/uiautomator2/blob/master/uiautomator2/__init__.py

**Comment by codeskyblue** [comment]
which line of code?

**Comment by xxxxlr** [comment]
Here https://github.com/xxxxlr/uiautomator2/commit/bffc86744ffa32f72849c6f8a8c5fcf3b8a94d57#diff-e3ac58825fae1a1915415aae83582391

**Comment by codeskyblue** [comment]
got it
