### ISSUE TITLE
Is there a way to stop a executing action?

### ISSUE THREAD

**Issue by xxxxlr** [openatx/android-uiautomator-server#12]
Hey @codeskyblue,

I have being using the lib for a while now and thanks for providing the handy lib and support!

However, I am facing a situation these days of not able to stop an exceuting a long task, something like 'scrollToEndOfTheContactList'.

The use case:

Python uiautomator sends a scrollToEnd request , then the uiautomator server sees the request and starts to execute it. But before it gets fully finished, the python uiautomator wants to stop it in order to do another request. The question is how to stop it without killing uiautomator server.

To my knowledge, I am not seeing how I could stop the executing task without killing the uiautomator and restart it. But killing it generates an exception on python uiautomator side('Uiautomation not connected' or 'GatewayError'). And this info is not enough to tell if this 'not connected' action is because I intentionally want to kill it or because it's really an exception causing by a temporary network issue. 

This is important in some cases when you need to decide if you want to retry the task since it's just a temporary network issue and a retry will just fix it or you just want to let it go since you killed it yourself.

So if you know any other methods to stop an executing task without killing uiautomator server, can you share some insight?

**Comment by codeskyblue** [comment]
seems there is no other way except kill python or kill uiautomator

**Comment by xxxxlr** [comment]
Thanks. I guess this is not a common use case. I will close it for now.
