### ISSUE TITLE
can set default theme to `BLACK`

### ISSUE THREAD

**Issue by yanqian** [openatx/android-uiautomator-server#13]
https://github.com/openatx/android-uiautomator-server/blob/master/app/src/main/java/com/github/uiautomator/MainActivity.java#L73
for this line, set default theme to `RED`, which will result in 1.0f brightness and battery-consuming.

Can help change to `BLACK`?

The background is, some phones as Samsung brand, will offline in atx-server after the screen is off. The way  to avoid offline is to keep the screen on all the time, but there is no such settings for Samsung phones. So alternative way is to start up the IdentifyActivity. The default setting is so battery consuming.

**Comment by codeskyblue** [comment]
use am start with params -e theme black
will launch identify activity with black

**Comment by yanqian** [comment]
OK, thanks.
