### ISSUE TITLE
dumpHierarchy低概率崩溃问题

### ISSUE THREAD

**Issue by codeskyblue** [openatx/android-uiautomator-server#21]
Ref: https://github.com/openatx/uiautomator2/issues/207

**Comment by codeskyblue** [comment]
最新测试结果
泰语乱码，中文OK
![image](https://user-images.githubusercontent.com/3281689/49065668-a9d32b80-f259-11e8-86f6-bd70ed87e9de.png)

**Comment by mingyuan-xia** [comment]
fixed with pr
