### ISSUE TITLE
Launch atx-agent daemon via start atx-agent button

### ISSUE THREAD

**Issue by citymaster** [openatx/android-uiautomator-server#25]
是否可以在UI做一个打开atx-agent服务进程的按键？
- 首先，我看到uiautomator代码启动atx-agent的代码是：atx-agent server -d
- 然后，我不是很理解这个为什么不做到app里面，即app启动时，直接启动atx-agent服务进程，这样可以免去连接usb使用adb才能启动，真正实现无线测试。

**Comment by citymaster** [comment]
我貌似看到答案了，是不是surface_control截图需要root权限，然后需要adb shell来给权限，所以这里不做启动部分，是这样么？

**Comment by codeskyblue** [comment]
apk属于安卓系统的底层，没什么权利
