### ISSUE TITLE
有没有什么方式在atx app里运行atx-agent可执行文件

### ISSUE THREAD

**Issue by codematrixer** [openatx/android-uiautomator-server#55]
如题， 我想做一个功能，比如在atx app的界面上启动atx-agent，是否可行？

我试了一圈没有成功，提示权限问题，无法在app内运行可执行文件

另外atx界面上的「停止atx-agent」的功能并没有生效。

**Comment by iTestinglab** [comment]
在Android中，运行shell命令时，默认情况下应用程序会以应用程序的用户身份运行。然而，由于安全限制，不能直接将应用程序的身份更改为shell用户,需要设备获得root权限，然后使用root用户执行命令。

有没有解决方法啊，坐等。
